from typing import Any, Protocol


class RatingsRepository(Protocol):
    def load(self) -> dict[str, Any]: ...
    def save(self, ratings: dict[str, Any]) -> None: ...


class PredictionsRepository(Protocol):
    def get(self, prediction_id: str) -> dict[str, Any] | None: ...
    def append(self, prediction: dict[str, Any]) -> None: ...


class GamesRepository(Protocol):
    def upsert(self, game: dict[str, Any], *, idempotency_key: str) -> None: ...
    def list_unsettled(self) -> list[dict[str, Any]]: ...


class ObjectRepository(Protocol):
    def get_bytes(self, key: str) -> bytes: ...
    def put_bytes_atomic(self, key: str, value: bytes) -> None: ...
